webService/tradefront1/tradefront1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('trademsg.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webService/tradefront1/trademsg/urls.py
from django.urls import path
from django.conf.urls import url, handler404, handler500

from . import views
app_name = 'trademsg'

urlpatterns = [
    path('',views.index, name='index'),
    path('buy/',views.buy, name='buy'),
    path('sell/',views.sell, name='sell'),
    path('set_apikey/',views.set_apikey, name='setapikey'),
    path('set_accesstoken/',views.token, name='token'),
    path('reset/',views.reset, name='reset'),
    url(r'^login/$', views.auth_views.login, {'template_name': 'registration/login.html'},name='login'),
    url(r'^logout/$', views.auth_views.logout,{'template_name': 'registration/logout.html'},name='logout'),

    path('trademsg_lf/',views.trademsglf, name='trademsglf'),
    path('trademsglfsql/',views.trademsglfsql, name='trademsglfsql'),
    path('trademsghfsql/',views.trademsghfsql, name='trademsghfsql'),
    path('set_access_token/',views.set_access_token, name='set_access_token'),

    path('momo/',views.momo, name='momo'),
    path('momo_high/',views.momo_high, name='momo_high'),



    path('inter_report/',views.inter_report, name='inter_report'),
    path('inter_report_high/',views.inter_report_high, name='inter_report_high'),
    path('trade_high/',views.trade_high, name='trade_high'),

    path('pending_orders/',views.pending_orders, name='pending_orders'),

]

webService/tradefront1/trademsg/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models



OT_CHOICES = (
    ("SL","SL"),
    ("Limit","Limit"),

)
class TradeMessage(models.Model):
    date_time = models.DateTimeField(db_column='Date_time')  # Field name made lowercase.
    script = models.CharField(max_length=150)
    close_price = models.FloatField()
    trade_pos = models.CharField(max_length=50)
    entry_price = models.FloatField()
    sl = models.FloatField(db_column='SL')  # Field name made lowercase.
    i_target_price = models.FloatField(db_column='I_target_price')  # Field name made lowercase.
    i_target_exit = models.FloatField(db_column='I_target_exit')  # Field name made lowercase.
    i_target_pl = models.FloatField(db_column='I_target_PL')  # Field name made lowercase.
    ii_target_price = models.FloatField(db_column='II_target_price')  # Field name made lowercase.
    ii_target_exit = models.FloatField(db_column='II_target_exit')  # Field name made lowercase.
    ii_target_pl = models.FloatField(db_column='II_target_PL')  # Field name made lowercase.
    trailing_exit = models.FloatField()
    trailing_float = models.FloatField()
    share_float = models.FloatField()

    class Meta:
        managed = True
        db_table = 'trade_message'


class APIINFO(models.Model):
    no = models.IntegerField()
    api_key = models.CharField(max_length=250,default="l5x8ay13aegnq946")
    api_token = models.CharField(max_length=250)
    dattime = models.DateTimeField()
    order_type = models.CharField(max_length=50,choices=OT_CHOICES,default="SL")
    script_exposure = models.IntegerField(default=1)
    cushion_price = models.IntegerField(null=True)

    class Meta:
        managed = True
        db_table = 'trade_apiinfo'


class TradeMessageHFloat(models.Model):
    date_time = models.DateTimeField(db_column='Date_time')  # Field name made lowercase.
    script = models.CharField(max_length=150)
    close_price = models.FloatField()
    trade_pos = models.CharField(max_length=50)
    entry_price = models.FloatField()
    sl = models.FloatField(db_column='SL')  # Field name made lowercase.
    i_target_price = models.FloatField(db_column='I_target_price')  # Field name made lowercase.
    i_target_exit = models.FloatField(db_column='I_target_exit')  # Field name made lowercase.
    i_target_pl = models.FloatField(db_column='I_target_PL')  # Field name made lowercase.
    ii_target_price = models.FloatField(db_column='II_target_price')  # Field name made lowercase.
    ii_target_exit = models.FloatField(db_column='II_target_exit')  # Field name made lowercase.
    ii_target_pl = models.FloatField(db_column='II_target_PL')  # Field name made lowercase.
    trailing_exit = models.FloatField()
    trailing_float = models.FloatField()
    share_float = models.FloatField()

    class Meta:
        managed = True
        db_table = 'trade_messageHFloat'

webService/tradefront1/trademsg/views.py
from django.shortcuts import render,redirect
from .models import TradeMessage,TradeMessageHFloat
from django.urls import reverse
from django.contrib.auth import views as auth_views
from .models import APIINFO
import logging
from kiteconnect import KiteConnect
import requests

from datetime import datetime
import csv
import json

from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from django.contrib.auth.decorators import login_required
import logging

logger = logging.getLogger(__name__)
import os



apiKey = None
accessToken = None
#

kite = None
# KiteConnect(api_key=apiKey)


dir_path = os.path.dirname(os.path.realpath(__file__))
print(dir_path)

# Redirect the user to the login url obtained
# from kite.login_url(), and receive the request_token
# from the registered redirect url after the login flow.
# Once you have the request_token, obtain the access_token
# as follows.

# kite.set_access_token(accessToken)


# Create your views here. Question.objects.order_by('-pub_date')[:5]

from django.http import HttpResponse,JsonResponse


def how_many_seconds_until_midnight():
    """Get the number of seconds until midnight."""
    n = datetime.now()
    n.hour
    return ((24 - n.hour - 1) * 60 * 60) + ((60 - n.minute - 1) * 60) + (60 - n.second)

@csrf_exempt
@login_required
def index(request):


    try:
        p = APIINFO.objects.latest('id')
        print(datetime.now())
        return render(request, 'trademsg/index.html',context={"data":p})
    except:
        return redirect(reverse('trademsg:set_access_token'))

@csrf_exempt
@login_required
def pending_orders(request):

    p = APIINFO.objects.latest('id')

    apiKey = p.api_key
    accessToken = p.api_token
    kite = KiteConnect(api_key=apiKey)
    kite.set_access_token(accessToken)



    if request.method == "POST":
        KiteConnect.cancel_order(kite,request.POST["var"],request.POST["oid"])



    kite.orders()



    print(datetime.now())
    return render(request, 'trademsg/pending_orders.html', context={"orders": kite.orders()})







@csrf_exempt
@login_required
def trademsglf(request):
    return render(request,'trademsg/trademsglive.html')

@csrf_exempt
@login_required
def trademsglfsql(request):
    q = TradeMessage.objects.order_by('-date_time')[:100]
    return render(request, 'trademsg/trademsg.html',context = {"data":q})

@csrf_exempt
@login_required
def trademsghfsql(request):
    q = TradeMessageHFloat.objects.order_by('-date_time')[:100]
    return render(request, 'trademsg/trademsg.html',context = {"data":q})




@csrf_exempt
@login_required
def set_access_token(request):

    apii_key = 'l5x8ay13aegnq946'

    if request.method == "POST":


        accessToken = request.POST["access_token"]

        if "order_type" in request.POST:

            OT = request.POST["order_type"]
        else:
            OT = "SL"

        if "script_exp" in request.POST:
            se = int(request.POST["script_exp"])
        else:
            se = 1

        if "cup" in request.POST:
            cp = int(request.POST["cup"])
        else:
            cp = 1





        p = APIINFO(no=1, api_key=apii_key, api_token=request.POST["access_token"],
                    dattime=datetime.now(),order_type=OT,script_exposure=se,cushion_price=cp)
        p.save()
        return redirect(reverse('trademsg:index'))

    else:
        try:
            p = APIINFO.objects.latest('id')
            kite = KiteConnect(api_key=apii_key)
            r = requests.get(kite.login_url())
            return render(request, 'trademsg/set_access.html', context={"url": kite.login_url(), 'data': r.text,'dd':p})


        except:

            kite = KiteConnect(api_key=apii_key)
            r = requests.get(kite.login_url())
            return render(request, 'trademsg/set_access.html', context={"url": kite.login_url(), 'data': r.text})



@csrf_exempt
@login_required
def momo(request):


    return render(request, 'trademsg/momo.html')


@csrf_exempt
@login_required
def momo_high(request):


    return render(request, 'trademsg/momo_high.html')


@csrf_exempt
@login_required
def inter_report(request):


    return render(request, 'trademsg/report.html')

@csrf_exempt
@login_required
def inter_report_high(request):


    return render(request, 'trademsg/report_high.html')

@csrf_exempt
@login_required
def trade_high(request):


    return render(request, 'trademsg/trade_high.html')




@api_view(['GET', 'POST'])
@csrf_exempt
def buy(request):

    p = APIINFO.objects.latest('id')

    apiKey = p.api_key
    accessToken = p.api_token
    kite = KiteConnect(api_key=apiKey)
    kite.set_access_token(accessToken)

    r = requests.get(''.join(
        ["https://api.kite.trade/instruments/NSE/", request.POST["script"], "?api_key=", apiKey, '&access_token=',
         accessToken]))

    print(''.join(
        ["https://api.kite.trade/instruments/NSE/", request.POST["script"], "?api_key=", apiKey, '&access_token=',
         accessToken]))

    # r = requests.get("https://api.kite.trade/instruments/MCX/SILVERMIC18AUGFUT?api_key=l5x8ay13aegnq946&access_token=5978ylw21tvnnvs3jallyt9r98yw6zbj")
    v = json.loads(r.text)

    print(v)
    print(p.order_type)

    trigPrice = v["data"]["depth"]["sell"][0]["price"] + 0.20
    Price = trigPrice + (trigPrice * (p.cushion_price/100))
    script_exp = int(round(p.script_exposure / v["data"]["depth"]["sell"][0]["price"]))

    not_mis = False

    with open(''.join([dir_path,"/mis_blocked.csv"])) as csvfile:
        readCSV = csv.reader(csvfile, delimiter=',')
        for row in readCSV:
            if(str(row[0])==request.POST["script"]):
                not_mis = True



    if (p.order_type == "SL"):
        if not_mis is True:

            try:
                order_id = kite.place_order(price=round(Price,1), trigger_price=trigPrice,
                                            tradingsymbol=request.POST["script"], variety=kite.VARIETY_REGULAR,
                                            exchange=kite.EXCHANGE_NSE,
                                            transaction_type=kite.TRANSACTION_TYPE_BUY,
                                            quantity=script_exp,
                                            order_type=kite.ORDER_TYPE_SL,
                                            product=kite.PRODUCT_CNC)


                logging.info("Order placed. ID is: {}".format(order_id))

                return JsonResponse({'orderId': p.order_type})
            except Exception as e:
                logging.info("Order placement failed: {}".format(e))
                return JsonResponse({'orderFailed': "Failed"})

        else:

            try:
                order_id = kite.place_order(price=round(Price,1), trigger_price=trigPrice,
                                            tradingsymbol=request.POST["script"], variety=kite.VARIETY_REGULAR,
                                            exchange=kite.EXCHANGE_NSE,
                                            transaction_type=kite.TRANSACTION_TYPE_BUY,
                                            quantity=script_exp,
                                            order_type=kite.ORDER_TYPE_SL,
                                            product=kite.PRODUCT_MIS)


                logging.info("Order placed. ID is: {}".format(order_id))

                return JsonResponse({'orderId': order_id})
            except Exception as e:
                logging.info("Order placement failed: {}".format(e))
                return JsonResponse({'orderFailed': "Failed"})
    else:
        print("Working")

        lprice = v["data"]["depth"]["sell"][0]["price"] + v["data"]["depth"]["sell"][0]["price"] * (p.cushion_price/100)
        if not_mis is True:

            try:
                order_id = kite.place_order(price=round(lprice,1),
                                            tradingsymbol=request.POST["script"], variety=kite.VARIETY_REGULAR,
                                            exchange=kite.EXCHANGE_NSE,
                                            transaction_type=kite.TRANSACTION_TYPE_BUY,
                                            quantity=script_exp,
                                            order_type=kite.ORDER_TYPE_LIMIT,
                                            product=kite.PRODUCT_CNC)

                logging.info("Order placed. ID is: {}".format(order_id))

                return JsonResponse({'orderId': order_id})
            except Exception as e:
                logging.info("Order placement failed: {}".format(e))
                return JsonResponse({'orderFailed': "Failed"})

        else:

            try:
                order_id = kite.place_order(price=round(lprice,1),
                                            tradingsymbol=request.POST["script"], variety=kite.VARIETY_REGULAR,
                                            exchange=kite.EXCHANGE_NSE,
                                            transaction_type=kite.TRANSACTION_TYPE_BUY,
                                            quantity=script_exp,
                                            order_type=kite.ORDER_TYPE_LIMIT,
                                            product=kite.PRODUCT_MIS)

                logging.info("Order placed. ID is: {}".format(order_id))

                return JsonResponse({'orderId': order_id})
            except Exception as e:
                logging.info("Order placement failed: {}".format(e))
                return JsonResponse({'orderFailed': "Failed"})







    #https://api.kite.trade/instruments/NSE/INFY?api_key=l5x8ay13aegnq946&access_token=5978ylw21tvnnvs3jallyt9r98yw6zbj


@csrf_exempt
def set_apikey(request):


    global kite
    global apiKey



    if  request.method == "POST":


        apiKey = request.POST["key"]

        request.session['apikey'] = apiKey

        kite = KiteConnect(api_key=apiKey)
        r = requests.get(kite.login_url())

webService/tradefront1/trademsg/templates/trademsg/index.html
<!DOCTYPE html>


<html>
    <head>
        <title>Entity Vibes - Trade Front</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <style>
            .color1 {
                background-color :white !important;
            }
            .color2 {
                background-color : #cccccc !important;
            }
            a {
                text-decoration: none !important;
            }
            .panel-body {
                padding-top: 40px;
                padding-bottom: 40px;
                text-align: center;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                <a class="navbar-brand" href="{% url 'trademsg:index' %}">Entity Vibes</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class><a class="navbar-brand" href="{% url 'trademsg:set_access_token' %}">||  Set Access Token (Last Updated on: {{ data.dattime }})</a></li>
            <li class><a class="navbar-brand" href="{% url 'trademsg:pending_orders' %}">||  Pending Orders</a></li>


        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'trademsg:logout' %}">Logout</a></li>
        </ul>
      </div>
    </div>


                    <!--<ul class="nav navbar-nav">-->
                        <!--<li>-->
                            <!--
                        <!--</li>-->
                        <!--<li>-->
                            <!---->
                        <!--</li>-->
                    <!--</ul>-->
                   <!--<ul class="nav navbar-nav" style="float: right">-->
            <!--<li></li>-->
          <!--</ul>-->








                </div>
<!--                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="index.html" target="_blank">Momo Scanner</a></li>
                        <li><a href="trade.html" target="_blank">Trade Message </a></li>
                        <li><a href="report.html" target="_blank">Intermediate Report</a></li>
                    </ul>
                </div>-->
            </div>
        </nav>

        <div class="container">
            <h3>Low Float</h3>
            <div class="row">
                <div class="col-lg-4">
                    <a href="{% url 'trademsg:momo' %}" target="_blank">
                        <div class="panel panel-primary">
                            <div class="panel-body">Momo Scanner</div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4">
                    <a href="{% url 'trademsg:trademsglf' %}" target="_blank">
                        <div class="panel panel-primary">
                            <div class="panel-body">Trade Message</div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4">
                    <a href="{% url 'trademsg:inter_report' %}" target="_blank">
                        <div class="panel panel-primary">
                            <div class="panel-body">Intermediate Report</div>
                        </div>
                    </a>
                </div>
            </div>
        </div>

        <div class="container">
            <h3>High Float</h3>
            <div class="row">
                <div class="col-lg-4">
                    <a href="{% url 'trademsg:momo_high' %}" target="_blank">
                        <div class="panel panel-primary">
                            <div class="panel-body">Momo Scanner</div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4">
                    <a href="{% url 'trademsg:trade_high' %}"  target="_blank">
                        <div class="panel panel-primary">
                            <div class="panel-body">Trade Message</div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4">
                    <a href="{% url 'trademsg:inter_report_high' %}" target="_blank">
                        <div class="panel panel-primary">
                            <div class="panel-body">Intermediate Report</div>
                        </div>
                    </a>
                </div>
            </div>
        </div>

        <script src="js/jquery-2.1.1.js"></script>
        <script src="js/bootstrap.min.js"></script>
    </body>
</html>

webService/tradefront1/trademsg/templates/trademsg/pending_orders.html
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>

{% for each in orders%}

    {% if each.status == "TRIGGER PENDING" %}
<b>orderID;</b>
{{ each.order_id }}



<b>Status:</b>
{{ each.status}}

<b>Script:</b>
{{ each.tradingsymbol }}

        <b>Cancle:</b>
         <form action="." method='post'>

         <input type='text' name='oid' value="{{ each.order_id }}" hidden>
             <input type='text' name='var' value="{{ each.variety }}" hidden>
         <input type='submit' value='Cancel'>
         </form>
<br>
<br>

    {% endif %}
{% endfor %}


</body>
</html>

webService/tradefront1/trademsg/templates/trademsg/set_apikey.html
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>

<form action="{% url 'trademsg:setapikey' %}" method='post'>
    ApiKey:
    <input type='text' name='key'>
    <br>
    <input type='submit' value='submit'>
</form>

</body>
</html>

webService/tradefront1/trademsg/templates/trademsg/trademsg.html
<!DOCTYPE html>
<html>
    <head>
        <title>Trade Message</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <link href="css/dataTables/datatables.min.css" rel="stylesheet"/>
        <!--<link href="css/dataTables/dataTables.bootstrap.css" rel="stylesheet"/>-->
        <link href="css/dataTables/dataTables.responsive.css" rel="stylesheet"/>
        <link href="css/dataTables/dataTables.tableTools.min.css" rel="stylesheet"/>

        <script src="js/bootstrap.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="js/dataTables/jquery.dataTables.js"></script>
        <script src="js/dataTables/dataTables.bootstrap.js"></script>
        <script src="js/dataTables/dataTables.responsive.js"></script>
        <script src="js/dataTables/dataTables.tableTools.min.js"></script>
        <script src="js/dataTables/datatables.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/interactjs@1.3.3/dist/interact.min.js"></script>

        <script src="js/stomp.js"></script>
        <script type="text/javascript">
            function myFunction(beforeCount) {
                var input, filter, table, tr, td, i,j,filters,flag,afterCount;
                input = document.getElementById("myInput");
                filter = input.value.toUpperCase();
                if(filter != '') {
                    filters = filter.split(",");
                    table = document.getElementById("myTable");
                    tr = table.getElementsByTagName("tr");
                    for (i = 0; i < tr.length; i++) {
                        td = tr[i].getElementsByTagName("td")[0];
                        if (td) {
                            flag = 0;
                            for(j = 0;j < filters.length;j++) {
                                if(filters[j] != '') {
                                    if (td.innerHTML.toUpperCase().indexOf(filters[j]) > -1) {
                                        tr[i].style.display = "";
                                        flag = 1;
                                        break;
                                    }
                                }
                            }
                            if(flag === 0) {
                                tr[i].style.display = "none";
                            }
                        }
                    }
                    afterCount =  $('tr').filter(function() {
                        return $(this).css('display') !== 'none';
                    }).length;
                    if(afterCount > beforeCount) {
                        var audio = new Audio('notification/open-ended.mp3');
                        audio.play();
                    }
                } else {
                    input = document.getElementById("myInput");
                    filter = input.value.toUpperCase();
                    table = document.getElementById("myTable");
                    tr = table.getElementsByTagName("tr");
                    for (i = 0; i < tr.length; i++) {
                        td = tr[i].getElementsByTagName("td")[0];
                        if (td) {
                            if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                              tr[i].style.display = "";
                            } else {
                              tr[i].style.display = "none";
                            }
                        }
                    }
                }
            }
        </script>

        <script type="text/javascript">





    function buy(val){
//      $('.modal-content').append(`
//
//      <form action="/action_page.php">
//   First name:<br>
//   <input type="text" value="Mickey"><br>
//   Last name:<br>
//   <input type="text" name="lastname" value="Mouse"><br><br>
//   <input type="submit" value="Submit">
// </form>
//
//
//      `)
//
//
//          var modal = document.getElementById('myModal');
//         modal.style.display = "block";
//         var span = document.getElementsByClassName("close")[0];
//         span.onclick = function() {
//     modal.style.display = "none";
//      }
//

        console.log(val);

            $.post("{% url 'trademsg:buy' %}", {
            'script':val,"csrfmiddlewaretoken":'{{csrf_token}}',

        }, function (data) {
            console.log(data)
                alert(data);
        });

  console.log(val);
}

 function sell(val){

        $.post("{% url 'trademsg:sell' %}", {
            'script':val,"csrfmiddlewaretoken":'{{csrf_token}}',

        }, function (data) {
            console.log(data);
            alert(data.orderId);
        });
  console.log(val);
}
</script>
        <style>
            .color1 {
                background-color :white !important;
            }
            .color2 {
                background-color : #cccccc !important;
            }
            .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
}

/* The Close Button */
.close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
}
        </style>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'trademsg:set_access_token' %}">Entity Vibes</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'trademsg:trademsglf' %}" target="_blank">Trade Message</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <input id="tr-color" value="color1" type="hidden"/>
        <div id="trade" class="col-lg-12">
            <div class="row form-horizontal">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="symbol" class="col-sm-3 control-label">
                            Filter
                        </label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="myInput" onkeyup="myFunction(9999999999)" placeholder="Script / Trade Pos" value="no_tradelong,shortlong,">
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="symbol" class="col-sm-12 control-label">
                            Filter Ex : script1,script3,tradepos1,tradepos2
                        </label>
                    </div>
                </div>
            </div>

            <table class="table table-bordered" id="myTable">
                <thead>
                    <tr>
                        <th style="display: none;">Filter Column</th>
                        <th style="min-width: 10px;">Date Time</th>
                        <th style="width: 20%">Script</th>
                        <th>Close Price</th>
                        <th>Trade Pos</th>
                        <th>Entry Price</th>
                        <th>SL</th>
                        <th>I-Target Price</th>
                        <th>I-Target Exit</th>
                        <th>I-TargetP/L</th>
                        <th>II-Target Price</th>
                        <th>II-Target Exit</th>
                        <th>II-Target P/L</th>
                        <th>Trailing Exit</th>
                        <th>Trailing P/L</th>
                        <th>Share Float</th>
                    </tr>
                </thead>
                <tbody id="data-trade">

                   {% for each in data %}
  <tr>

    <td>{{ each.date_time|date:'M d H:i a' }}</td>
    <td>{{  each.script }} <button  class="btn btn-primary btn-sm" type="button" value="{{ each.script }}" onclick="buy(this.value);">buy</button> <button type="button" class="btn btn-danger btn-sm" value="{{ each.script }}" onclick="sell(this.value);">sell</button></td>
    <td>{{ each.close_price }}</td>
      <td>{{ each.trade_pos }}</td>
      <td>{{ each.entry_price }}</td>
      <td>{{ each.sl }}</td>
      <td>{{ each.i_target_price }}</td>
      <td>{{ each.i_target_exit }}</td>
      <td>{{ each.i_target_pl }}</td>
      <td>{{ each.ii_target_price }}</td>
      <td>{{ each.ii_target_exit }}</td>
      <td>{{ each.ii_target_pl }}</td>
      <td>{{ each.trailing_exit }}</td>
      <td>{{  each.trailing_float }}</td>
      <td>{{ each.share_float }}</td>

  </tr>

  {% endfor %}

                </tbody>
            </table>
        </div>

<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>Some text in the Modal..</p>
    <input type="text">
  </div>

</div>




    </body>
</html>